/** Compatibility implementation is owned by the shared package; preserve this import contract. */
export {
  createVllmResponsesCompatibilityRule,
  stripToolUseProviderSpecificFieldsFromBody,
  stripToolUseProviderSpecificFields,
  stripEncryptedContentFromBody,
  stripImageGenerationItemsWithoutIdFromBody,
  stripEmptyThinkingFromBody,
  stripEmptyTextFromBody,
  stripEmptyAssistantMessagesFromBody,
  dedupeDuplicateToolUseIdsFromBody,
  dedupeDuplicateToolUseIds,
  repairToolExchangeAdjacencyFromBody,
  repairToolExchangeAdjacency,
  repairToolExchangeStructureFromBody,
  replaceToolResultImagesWithNotice,
  compactOversizedImageHistory,
  stripNonAnthropicFields,
  createActiveStripTransform,
  createEncryptedContentRecoveryRule,
  createImageGenerationIdRecoveryRule,
  createToolUseProviderSpecificFieldsRecoveryRule,
  createEmptyThinkingRecoveryRule,
  createEmptyTextRecoveryRule,
  createEmptyAssistantMessageRecoveryRule,
  createDuplicateToolUseIdRecoveryRule,
  createToolExchangeAdjacencyRecoveryRule
} from '@cindy/model-compat';
