import type { SettingsSearchModule } from './settingsSearchTypes';

/** Search metadata for cards rendered inside the long settings pages. */
export default {
  id: 'personalization-details',
  order: 31,
  entries: [
    { id: 'settings.composer.sendShortcut.label', fallbackTargetId: 'settings-composer', tab: 'general', targetId: 'settings-composer', titleKey: 'settings.composer.sendShortcut.label', sectionKey: 'settings.sections.composer', descriptionKey: 'settings.composer.sendShortcut.hint', aliases: ['send shortcut', 'enter to send', '发送快捷键'] },
    { id: 'settings.memory.maker.label', fallbackTargetId: 'settings-search-target-personalization-memory', tab: 'personalization', targetId: 'settings-search-target-personalization-memory', titleKey: 'settings.memory.maker.label', sectionKey: 'settings.sections.memory', descriptionKey: 'settings.memory.maker.description', aliases: ['maker memory', '记忆'] },
    { id: 'settings.memory.agents.claude-code.label', fallbackTargetId: 'settings-search-target-personalization-memory', tab: 'personalization', targetId: 'settings-search-target-personalization-memory', titleKey: 'settings.memory.agents.claude-code.label', sectionKey: 'settings.sections.memory' },
    { id: 'settings.memory.agents.codex.label', fallbackTargetId: 'settings-search-target-personalization-memory', tab: 'personalization', targetId: 'settings-search-target-personalization-memory', titleKey: 'settings.memory.agents.codex.label', sectionKey: 'settings.sections.memory' },
    { id: 'settings.memory.agents.pi.label', fallbackTargetId: 'settings-search-target-personalization-memory', tab: 'personalization', targetId: 'settings-search-target-personalization-memory', titleKey: 'settings.memory.agents.pi.label', sectionKey: 'settings.sections.memory' },
    { id: 'settings.auxiliaryModels.title', fallbackTargetId: 'settings-search-target-personalization-auxiliary-models', tab: 'personalization', targetId: 'settings-search-target-personalization-auxiliary-models', titleKey: 'settings.auxiliaryModels.title', sectionKey: 'settings.sections.auxiliaryModels', descriptionKey: 'settings.auxiliaryModels.description', aliases: ['auxiliary model', '辅助模型'] },
    { id: 'settings.auxiliaryModels.preferred.label', fallbackTargetId: 'settings-search-target-personalization-auxiliary-models', tab: 'personalization', targetId: 'settings-search-target-personalization-auxiliary-models', titleKey: 'settings.auxiliaryModels.preferred.label', sectionKey: 'settings.sections.auxiliaryModels' },
    { id: 'settings.auxiliaryModels.fallback1.label', fallbackTargetId: 'settings-search-target-personalization-auxiliary-models', tab: 'personalization', targetId: 'settings-search-target-personalization-auxiliary-models', titleKey: 'settings.auxiliaryModels.fallback1.label', sectionKey: 'settings.sections.auxiliaryModels' },
    { id: 'settings.auxiliaryModels.fallback2.label', fallbackTargetId: 'settings-search-target-personalization-auxiliary-models', tab: 'personalization', targetId: 'settings-search-target-personalization-auxiliary-models', titleKey: 'settings.auxiliaryModels.fallback2.label', sectionKey: 'settings.sections.auxiliaryModels' },
    { id: 'settings.compaction.title', fallbackTargetId: 'settings-search-target-personalization-compaction', tab: 'personalization', targetId: 'settings-search-target-personalization-compaction', titleKey: 'settings.compaction.title', sectionKey: 'settings.sections.compaction', aliases: ['compaction', '上下文压缩'] },
    { id: 'settings.compaction.card', fallbackTargetId: 'settings-search-target-personalization-compaction', tab: 'personalization', targetId: 'settings-search-target-personalization-compaction', titleKey: 'settings.compaction.card', sectionKey: 'settings.sections.compaction' },
    { id: 'settings.compaction.piCard', fallbackTargetId: 'settings-search-target-personalization-compaction', tab: 'personalization', targetId: 'settings-search-target-personalization-compaction', titleKey: 'settings.compaction.piCard', sectionKey: 'settings.sections.compaction' },
    { id: 'settings.terminalShell.card.label', fallbackTargetId: 'settings-search-target-personalization-terminal-shell', tab: 'personalization', targetId: 'settings-search-target-personalization-terminal-shell', titleKey: 'settings.terminalShell.card.label', sectionKey: 'settings.sections.terminalShell', aliases: ['terminal', 'shell', '终端'] },
    { id: 'settings.linkOpen.web.label', fallbackTargetId: 'settings-search-target-personalization-link-open', tab: 'personalization', targetId: 'settings-search-target-personalization-link-open', titleKey: 'settings.linkOpen.web.label', sectionKey: 'settings.sections.linkOpen', aliases: ['open in sidebar', '内置侧栏'] },
    { id: 'settings.linkOpen.local.label', fallbackTargetId: 'settings-search-target-personalization-link-open', tab: 'personalization', targetId: 'settings-search-target-personalization-link-open', titleKey: 'settings.linkOpen.local.label', sectionKey: 'settings.sections.linkOpen', aliases: ['open externally', '系统浏览器'] },
    { id: 'settings.streamFade.label', fallbackTargetId: 'settings-search-target-personalization-stream-fade', tab: 'personalization', targetId: 'settings-search-target-personalization-stream-fade', titleKey: 'settings.streamFade.label', sectionKey: 'settings.sections.streamFade', aliases: ['fade in', '流式淡入'] },
    { id: 'settings.compatMode.title', fallbackTargetId: 'settings-search-target-personalization-tips', tab: 'personalization', targetId: 'settings-search-target-personalization-tips', titleKey: 'settings.compatMode.title', sectionKey: 'settings.sections.compatMode' },
  ],
} satisfies SettingsSearchModule;
