/** Compatibility implementation is owned by the shared package; preserve this import contract. */
export {
  isResponsesImageContentPartType,
  isUnsupportedResponsesImageErrorPayload,
  UnsupportedResponsesFeatureError
} from '@cindy/model-compat';
export type {
  ResponsesInputTextPart,
  ResponsesInputImagePart,
  ResponsesInputFilePart,
  ResponsesInputAudioPart,
  ResponsesContentPart,
  ChatToolCallExtraContent,
  ResponsesInputItem,
  ResponsesFunctionTool,
  ResponsesCustomTool,
  ResponsesNamespaceTool,
  ResponsesRequest,
  ChatTextContentPart,
  ChatImageUrlContentPart,
  ChatFileContentPart,
  ChatInputAudioContentPart,
  ChatUserContentPart,
  ChatTextMessage,
  ChatUserMessage,
  ChatAssistantMessage,
  ChatToolMessage,
  ChatMessage,
  ChatCompletionsRequest,
  ChatDeveloperRole,
  ChatMaxTokensField,
  ChatImageInput,
  ChatFileInput,
  ChatAudioInput,
  ChatReasoningField,
  ChatReasoningHistoryField,
  ChatPassthroughField,
  ChatBridgeCapabilities,
  ChatBridgeLogger,
  ChatBridgeUpstreamErrorInfo,
  ChatBridgeProviderConfig,
  ChatBridgeHandleArgs,
  ResponsesChatBridgeHandler
} from '@cindy/model-compat';
